FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y mariadb-server mariadb-client iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy configuration files
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/init-db.sh /usr/local/bin/init-db.sh

RUN chmod 755 /usr/local/bin/init-db.sh && \
    chown mysql:mysql /usr/local/bin/init-db.sh

# Create mysql data directory and set permissions
RUN mkdir -p /run/mysqld && \
    chown -R mysql:mysql /run/mysqld && \
    chown -R mysql:mysql /var/lib/mysql && \
    chown -R mysql:mysql /etc/mysql/ && \
    mkdir -p /var/log/mysql && \
    chown mysql:mysql /var/log/mysql

EXPOSE 3306

CMD ["/usr/local/bin/init-db.sh"]

