FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y \
    php8.2-fpm \
    php8.2-mysql \
    wget \
    mariadb-client \
    tar iputils-ping && \
    rm -rf /var/lib/apt/lists/*

#download wp- cli (tolbox to set up wordpress from terminal)
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

#create dir for Wordpress files
RUN mkdir -p /var/www/html

#copy and run initialisation script
COPY ./tools/init-wp.sh /usr/local/bin/init-wp.sh
RUN chmod +x /usr/local/bin/init-wp.sh

# Configura PHP-FPM to listen on port 9000
RUN sed -i 's|listen = /run/php/php8.2-fpm.sock|listen = 9000|' /etc/php/8.2/fpm/pool.d/www.conf


EXPOSE 9000

#set script as entry point. It is the first thing that runs in the docker file
ENTRYPOINT ["init-wp.sh"]

#it defines the args that are passed inside the script to exec command
CMD ["php-fpm8.2", "-F"]
