FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y php php-fpm php-mysql wget tar && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/www/html && \
    wget https://wordpress.org/latest.tar.gz && \
    tar -xzf latest.tar.gz -C /var/www/html --strip-components=1 && \
    rm latest.tar.gz

COPY ./tools/wp-config.php /var/www/html/wp-config.php

# Configura PHP-FPM per usare TCP invece di socket Unix
RUN sed -i 's|listen = /run/php/php.*-fpm.sock|listen = 0.0.0.0:9000|' /etc/php/*/fpm/pool.d/www.conf

# Crea la directory per il PID file di PHP-FPM
RUN mkdir -p /run/php

EXPOSE 9000
CMD ["php-fpm", "-F"]
