FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y nginx openssl iputils-ping && \
    rm -rf /var/lib/apt/lists/*

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./tools/init_ssl.sh /init_ssl.sh
RUN chmod +x /init_ssl.sh && /init_ssl.sh

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
